### ISSUE TITLE
Storage extensions shut down before execution serializer is shutdown

### ISSUE THREAD

**Issue by johnou** [orbit/orbit#149]
Storage extensions are shut down before the execution serializer which means storage extensions that override cloud.orbit.lifecycle.Startable#stop and shut down connection pools etc. may cause problems for Actors which invoke writeState() inside deactivateAsync.

**Comment by JoeHegarty** [comment]
Do you see any reason we can't just move this later in the shutdown procedure? Nothing comes to mind so I'll do that assuming no objections.

**Comment by johnou** [comment]
After shutting down executionSerializer? or did you have something else in mind?

**Comment by JoeHegarty** [comment]
I think after executionSerializer is probably fine. I'll need to test it out.

**Comment by JoeHegarty** [comment]
Fix applied. Let me know if you have any further issues.
