### ISSUE TITLE
Orbit stage timer keeps JVM alive after failed startup

### ISSUE THREAD

**Issue by samskivert** [orbit/orbit#153]
If you create a stage, then go off to start other services (like Jetty), but those fail, you want to cleanly shut down the JVM, but Orbit is sticking a fork in that process.

`Stage` declares a `Timer` and creates it in the implicit constructor:

```java
    private Timer timer = new Timer("Orbit stage timer");
```

This causes a non-daemon thread to be started. So as soon as you "new Stage()" you are in a dangerous limbo state. You can't call Stage.shutdown() because the Stage isn't started yet, but you can't quit your JVM because there are non-daemon threads.

It would be ideal if Stage didn't create the timer until it was started. I'd submit this with a pull request, but I don't know how you want to handle that lazy initialization, so I'll leave this (hopefully simple) fix up to your discretion.

**Comment by JoeHegarty** [comment]
Looks like this is a duplicate. #154 is the issue I'll use
