### ISSUE TITLE
"Orbit stage timer" keeps JVM alive after failed startup

### ISSUE THREAD

**Issue by samskivert** [orbit/orbit#154]
If you create a stage, then go off to start other services (like Jetty), but those fail, you want to cleanly shut down the JVM, but Orbit is sticking a fork in that process.

`Stage` declares a `Timer` and creates it in the implicit constructor:

```java
    private Timer timer = new Timer("Orbit stage timer");
```

This causes a non-daemon thread to be started. So as soon as you "new Stage()" you are in a dangerous limbo state. You can't call Stage.shutdown() because the Stage isn't started yet, but you can't quit your JVM because there are non-daemon threads.

It would be ideal if Stage didn't create the timer until it was started. I'd submit this with a pull request, but I don't know how you want to handle that lazy initialization, so I'll leave this (hopefully simple) fix up to your discretion.

**Comment by JoeHegarty** [comment]
I'll fix this up in the morning. Definitely a bug.

**Comment by JoeHegarty** [comment]
Thanks for reporting this. I've fixed the described behavior, and also added support for people defining custom timers. That seems like it might be valuable if people want to wrap the timer with some metrics.

**Comment by samskivert** [comment]
👍🏼

**Comment by johnou** [comment]
@JoeHegarty could also run it as a daemon thread?

**Comment by samskivert** [comment]
Now you have that option since you can build your own timer, but as long as it's getting properly shutdown during normal Stage shutdown, I don't mind that it's non-daemon.

**Comment by johnou** [comment]
fwiw I also verified that if an exception is thrown from cleanup the exception _doesn't_ bubble up to the timer which would have killed the scheduled task.
