### ISSUE TITLE
Any roadmap for orbit

### ISSUE THREAD

**Issue by wenerme** [orbit/orbit#180]
I think orbit is workable but still far from complete or good enough.Is there any roadmao for orbit or WIP ?

**Comment by JoeHegarty** [comment]
Our primary goal with Orbit at this stage is stability. We don't have any major new features planned moving forward at this point in time.
What do you feel is missing from the framework?

**Comment by spinisetti** [comment]
I don't see any open issues, can you list any pending stability issues that you might have encountered?

**Comment by JoeHegarty** [comment]
I'm not aware of any major stability issues. The primary concern around stability right now is the Infinispan/JGroups layer that Orbit uses for clustering. Configuring that layer correctly for your use case is essential to getting stable and high performance from Orbit.
We're investigating ways to make this easier, including replacing those technologies with something different, but we don't currently have a timeline for this.

**Comment by wenerme** [comment]
The issues is there is no issues, feels like orbit is hibernated and inactive.

I try to use orbit as a drpc framework, but every function have to return a Task feels very cumbersome.An Actor is bind to id, so if a reference is created, all call is going to the same destination, I wish every call can go random peer.

**Comment by JoeHegarty** [comment]
The project isn't hibernated, but it has been fairly inactive recently. We're expecting to switch our focus back to orbit in the next few weeks so you should see the activity pick up. We are planning to launch major projects on the framework in the next 12 months so stability is very important to us.

Orbit is an implementation of the virtual actor framework as described in the Microsoft Orleans whitepaper. Returning a task in all cases is an important part of that model. 

For your node balancing, Orbit isn't really desired for that use case, but you can achieve something similar with a NoIdentity StatelessWorker. See https://github.com/orbit/orbit/wiki/Concepts%3A-Stateless-Workers

**Comment by wenerme** [comment]
Thanks, I will keep an eye on orbit, waiting for the big change.Orbit is good and stable enough for current usage, the ClusterPeer is so simple that I implement over Redis and Hazelcast in very short time.

**Comment by JoeHegarty** [comment]
Great. Please let me know if you have any other questions.
