### ISSUE TITLE
Upgrading a cluster (question)

### ISSUE THREAD

**Issue by crumblingworld** [orbit/orbit#196]
Hi

Thanks for the cool framework!

How can I make zero down time upgrades work? Say I have a cluster running happily and I want to introduce a new version of an actor? Ideally I'd add nodes with the new version of the Actor, while removing the old nodes and eventually all activations would be running the new version and no-one will have experienced any downtime.

I can make the actor's state be forward and backward compatible without too much drama, so that should deal with activation and deactivation. But what about changes to the Actor interface or implementation classes?

How do you see this process working?

Thanks again!

**Comment by JoeHegarty** [comment]
Hi,

Thanks for your question. Sorry for the slow response, I am currently travelling.

It's a good question and it's one that we've spent a lot of time thinking about.

You are correct that making actors able to load state in a forwards/backwards compatible way is the first step and it's quite easy to achieve. 

In terms of changing the Actor API, it is a lot trickier. 
Introducing new APIs is fairly safe, the result of calling an actor without that API implemented (say he's activated on a node with the old version) will be an exception. Removing an API is similar but the other way around.
Changing an API is a much more difficult prospect and the behavior is effectively undefined as it depends a lot on the serialization method being used and other factors.
In all cases, the key thing is to test and ensure that your actors and code using them is able to tolerate the failures and has some way of recovering.

One common way that people who are using Orbit or similar frameworks use for upgrades is a straight VIP swap. For instance, if you are running on an elastic service like AWS, it's possible to spin up a replacement environment, drain the existing environment (let all requests finish, queue new requests in your load balancer or similar) and then bring the existing environment down and switch over to the new environment and flush the queue against it. 
This is effectively zero downtime but you do have a few seconds when requests are very slow as they are basically just queued.

I hope that gives you some idea of how you might achieve this. 
If you have other questions please let me know.

Thanks,
Joe

**Comment by crumblingworld** [comment]
Thanks Joe!

That's all great and what I was expecting :-)

Queues to the rescue ;-)

Cheers
Theo
