### ISSUE TITLE
[Query] Implementation Model

### ISSUE THREAD

**Issue by scibernix** [orbit/orbit#197]
Hello,

I went through the Orbit tutorials and the Orleans paper. I understand JGroups & Infinispan are used to manage distributed state. I have couple of questions:

- How are virtual actors implemented on JVM ? using green thread like concept ? bytecode manipulation ?
- Is there a concept of supervisor actor ? A single actor can have multiple children, for example, multiple requests on the same service URL will spawn multiple actors having different IDs.
- How do you manage Actors ? Is there a management UI to control cluster - JMX ? 

Thanks

**Comment by JoeHegarty** [comment]
Hi,

Thanks for your questions.

Virtual actors in Orbit are basically just a class instance at the most basic level. All execution of messages on that actor is handled by the framework. There is effectively a threadpool and orbit spreads the message processing across that pool (guaranteeing the same actor won't run 2 messages at once) as required. This is what the defaultExecutionPoolSize in Stage is doing. 
The way Orbit actually implements this is fairly complex and uses bytecode generation & manipulation as well as routing everything through the orbit runtime to make sure it's all consistent and to ensure the guarantees are respected. 

In the virtual actor model there is really no concept of supervisor actors. One of the key concepts is that actors aways exist conceptually so there is really no concept of an actor being alive/dead etc. You can address an actor at any time and the framework will figure out how to make that happen.

Similar to above, there is no concept of actor lifetime in the traditional sense so you don't need to manage actors manually at all. The framework deals with retrieving actor state from backing storage, activating the actor and then paging it out (and back in) as required. 
The default behavior is that on the first message to an actor, state will be retrieved (or if no state exists, it will be default state) and the actor will be activated on the cluster, it will then process any further messages to that actor until it has been idle for 10 minutes, at which point it will deactivate and exist only in the backing storage again.

Hopefully that answers your questions. One of the hardest things to adapt to coming from a traditional actor framework when you come to the virtual actor framework is the lack of explicit lifetime and ownership and the idea that an actor always exists from the point-of-view of someone interacting with it.

Please let me know if you have any other questions.

Thanks,
Joe

**Comment by JoeHegarty** [comment]
Going to close this one. Please let me know if you have any further questions.
