### ISSUE TITLE
Streams batch subscribing and unsubscribing.

### ISSUE THREAD

**Issue by johnou** [orbit/orbit#199]
Instead of iterating over hundreds of items and generating lots of messages / write states to the storage provider it would be nice to be able to batch subscribe and unsubscribe from streams.

**Comment by JoeHegarty** [comment]
How do you envisage the API working?

**Comment by johnou** [comment]
Bit tricky wrt backwards compatibility but something basic like passing a collection / producer / consumer allowing the developer to register a set instead of one at a time.

**Comment by JoeHegarty** [comment]
I think this should be doable, just need to think of a way to do it that allows backwards compatibility and also makes sense when you are basically registering one processor across multiple objects.
I'll keep this open and hopefully can take a look soon.

**Comment by johnou** [comment]
We dropped streams in our project, feel free to close this issue.
