### ISSUE TITLE
Conflicting documentation with respect to timers

### ISSUE THREAD

**Issue by justinlang** [orbit/orbit#218]
The wiki page for timers states:
"Timers do not keep an actor activated and will disappear on deactivation."

However, the method comment for AbstractActor.registerTimer reads:
"The timer is automatically disposed on deactivation.  The timer calls will keep the actor active."

Do timers keep an actor active or not?

**Comment by justinlang** [comment]
I just did a quick test to see which behaviour occurs.  I created an actor and set up a recurring timer on a 15 second interval.  I added logging in the callable, and in the activateAsync and deactivateAsync methods.  The actor is deactivated after 10 minutes (default TTL for actors) and the timer stops.  So it seems like the method comment is inaccurate.

**Comment by JoeHegarty** [comment]
Thanks for the confirmation. That's the expected behaviour so the comment is indeed incorrect. I'll fix shortly. 
Thanks!
