### ISSUE TITLE
DefaultClassDictionary memory usage

### ISSUE THREAD

**Issue by johnou** [orbit/orbit#228]
In most scenarios cloud.orbit.actors.runtime.DefaultClassDictionary#getHashCodeToClassName is an OOM waiting to happen, let me know if you have any objections to removing it. 

Ideally I would like to explore another class finder that simply scans for actor interfaces and implementations at build time instead of runtime @quilombodigital had some ideas on that.. :)

**Comment by johnou** [comment]
@JoeHegarty ping.

**Comment by JoeHegarty** [comment]
What are the implications of removing this from your point of view?

**Comment by johnou** [comment]
Actually, removing it will break cloud.orbit.actors.extensions.json.JsonMessageSerializer..
