### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by ghost** [orbit/orbit#257]
Hi folks! I'm using the HelloWorld example (in java) in Windows with gradle. But I'm no successfully, the gradle wrapper is returning these erros
 
`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Jun 22, 2017 8:36:09 PM org.infinispan.remoting.transport.jgroups.JGroupsTransport start
INFO: ISPN000078: Starting JGroups channel orbit-helloworld-cluster
Jun 22, 2017 8:36:09 PM org.jgroups.stack.DiagnosticsHandler bindToInterfaces
WARNING: failed to join /224.0.75.75:7500 on net0: java.net.SocketException: Unrecognized Windows Sockets error: 0: no I
net4Address associated with interface=`

**Comment by armsnyder** [comment]
Can you provide more details about your setup? What HelloWorld example are you referring to? In the logs you pasted I only see warnings. Are there any other symptoms?

The only thing I can say for certain is that the SLF4J logs can be ignored - it's just telling you that you have not included a logger as a library / dependency.

**Comment by JoeHegarty** [comment]
Thanks for your report. As @armsnyder can you share some more information about your setup?
Are you using the orbit-samples helloworld or did you follow the tutorial?
