### ISSUE TITLE
What is best way to get Actor self reference ?

### ISSUE THREAD

**Issue by mryvz** [orbit/orbit#263]
How can i self invoke Actor internal  method ? 
for example in Akka i can invoke ;
`getSelf().tell(new MyPrivateMessage(),getSelf())`

**Comment by JoeHegarty** [comment]
You can just do `Actor.getReference(MyActor.class, actorIdentity())` from within an actor to get a reference, this would be useful if you want to send a message to yourself as in your example.

If you want to pass the reference somewhere you can just pass `this` and Orbit will handle turning that into a reference. `someOtherActor.addPlayer(this)` for example.
