### ISSUE TITLE
Documentation points to wrong location for JGroups config

### ISSUE THREAD

**Issue by pilt** [orbit/orbit#271]
Thanks for this interesting project! I'm just playing around so far to get acquainted with the virtual actor model.

[This page](https://github.com/orbit/orbit/wiki/Advanced%3A-JGroups-Cluster-Configuration) says that you should modify `classpath:/conf/jgroups.xml` but the default seems to be `classpath:/conf/udp-jgroups.xml` (in JGroupsClusterPeer).

That it's called udp-jgroups.xml makes me wonder if it's supposed to work over TCP. I just tried the Hello world example from the wiki with the configuration below and that worked however (originally found at https://github.com/belaban/JGroups/blob/master/conf/tcp.xml).

```xml
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="urn:org:jgroups"
        xsi:schemaLocation="urn:org:jgroups http://www.jgroups.org/schema/jgroups.xsd">
        <TCP bind_port="7800"
             recv_buf_size="${tcp.recv_buf_size:130k}"
             send_buf_size="${tcp.send_buf_size:130k}"
             max_bundle_size="64K"
             sock_conn_timeout="300"

             thread_pool.min_threads="0"
             thread_pool.max_threads="20"
             thread_pool.keep_alive_time="30000"/>

        <TCPPING async_discovery="true"
                 initial_hosts="${jgroups.tcpping.initial_hosts:localhost[7800],localhost[7801]}"
                 port_range="2"/>
        <MERGE3  min_interval="10000"
                 max_interval="30000"/>
        <FD_SOCK/>
        <FD timeout="3000" max_tries="3" />
        <VERIFY_SUSPECT timeout="1500"  />
        <BARRIER />
        <pbcast.NAKACK2 use_mcast_xmit="false"
                        discard_delivered_msgs="true"/>
        <UNICAST3 />
        <pbcast.STABLE desired_avg_gossip="50000"
                       max_bytes="4M"/>
        <pbcast.GMS print_local_addr="true" join_timeout="2000"/>
        <MFC max_credits="2M"
             min_threshold="0.4"/>
        <FRAG2 frag_size="60K"  />
        <!--RSVP resend_interval="2000" timeout="10000"/-->
        <pbcast.STATE_TRANSFER/>
</config>
```

**Comment by johnou** [comment]
I'll take care of this too.

**Comment by JoeHegarty** [comment]
FYI, you might also consider using the Redis clustering: https://github.com/orbit/orbit-redis-cluster

**Comment by pilt** [comment]
Thanks, that's interesting. I do think that if I ever made something serious I would prefer Redis over JGroups/Infinispan.

Personally mostly because I have zero experience of the latter but have used Redis as a message queue on many occasions, but also because I would run on AWS, GCP or some other env without native support for multicast, and would rather not run a separate node discovery service--easier to just start Redis on AWS ElastiCache and sleep well. Must admit that JGroups seems less boring though. :)

Thanks again!

**Comment by johnou** [comment]
Updated documentation.
