### ISSUE TITLE
task.cancel() has no effect on taks waiting in the queue.

### ISSUE THREAD

**Issue by mryvz** [orbit/orbit#273]
Hi,
i ve two actors Actor1 and Actor2. Actor2 m2 method is a long running method. Im calling  Actor2.m2() multiple times from actor1 and adding response task to a list. Sometimes i need to cancel waiting tasks (actor2.m2()) and i call task.cancel() for all tasks i already added list. But actor2 executes tasks i ve cancelled before. 
Does it mean , an actor method once called there is nothing i can do to stop it?

```java
interface Actor1 extends Actor {
  public Task<Void> m1();
  public Task<Void> cancel();
}
```
```java
interface Actor2 extends Actor{
// this is long running task
 public Task<Void> m2(String prm);
}
```

```java
class Actor1Impl extends AbstractActor implements Actor1 {
   private List<Task> taskCache = new ArrayList();   
   private Actor2 act2;
   public Task<Void> activateAsync(){
        act2 = Actor.getReference(Actor2.class);
   }

   public Task<Void>  m1(){
      taskCache.clear();
      for(int i=0;i<100;i++)
         taskCache.add(act1.m2());
      return Task.done();
   }
   public void cancel() {
       for(Task t:taskCache) {
        t.cancel();
       }
       taskCache.clear();
   }

}

```
Actor1 methods  is being called by JavaFX thread (a start and a cancel button).

Thanks.

**Comment by JoeHegarty** [comment]
I’m currently travelling but will be able to respond tomorrow. Sorry for the delay.

**Comment by mryvz** [comment]
i ve found a solution dont know but it is right way.
```java
interface MyTaskObserver<T> extends ActorObserver {
     public  Task<Void> isCancelled();
     public  Task<Void> complete(T t);
     public  Task<Void> completeWithError(Throwable t);
}
class DefaultTaskObserver<T> implements MyTaskObserver<T> {

      private CompletableFuture<T> fut= new CompletableFuture();

     public  Task<Void> isCancelled() {return Task.fromValue(cancel.get())}
     public  Task<Void> complete(T t) {
                fut.complate(t);
     }
     public  Task<Void> completeWithError(Throwable t) {
              fut.complateExceptionally(t);
      }

      AtomicBoolean cancel = new AtomicBoolean(false);
     public void cancel(){
         cancel.set(true);
         fut.complate(null);
     }
    public CompletableFuture<T> toFuture(){
             return fut;
   }
}
}

class MyActorImpl implements MyActor {
 ...
  ExecutorService myexec = ....;
   
   public Task<Void> doAsync(String myParam,MyAsyncObserver o) {
       
          myexec.submit( ()->{
               try {
                    if(o.isCancelled())return;
                             T retval;
                           ....
                          o.complate(retval);
                    }catch(Exception ex) {
                         o.complateExceptionally(ex);
                     }
        }

  }

}

```

**Comment by JoeHegarty** [comment]
In general as you discovered cancelling a running task isn't something Orbit supports.

This is because the task returned is actually just a promise for the result rather than the execution itself, this is because the Task may be running remotely from the current JVM so the local node doesn't really know anything about the status of the task until it gets a response (or no response at all).
Orbit generally expects tasks to be short running and when you make call to an actor it's a best-effort `at most once` call which may or may not get a result.

I'm curious what kind of operation you are performing where cancelling would be required?
It may be that you need to model this in a different way rather than using actor messages.

**Comment by mryvz** [comment]
I ve  an actor,  controls a machine over serial port (9600 baud).  1 message over serial has about 200 ms  req + resp time.   i need to send about 100 message in a row for loading purpose , and processing all them takes ~30 sec (for 3 machine connected  same port its timex3). if user select wrong job to load , (s)he has to wait 90 sec for job .  Cancelling task has no effect , messages continues being sending to serial port and blocking communication during this time.

**Comment by JoeHegarty** [comment]
It sounds like your use case doesn't really map into the virtual actor model very well.
In general, long running tasks (such as I/O) should not be tying up your actor. If your actor message takes say more than 1ms to process it is likely too long. The only exception is when you are chaining onto it for the thread safety guarantee (such as when saving to database).

In your case, it sounds like your actor should create a Job/Thread of its own and then hold on to a handle but not block the Orbit thread. You'd then have start/stop etc be messages you send to your actor which simply interact with your job. If the original caller of start wants to get a result you can use a Stream or Observer and send a message to the sender once the job is complete.

Does that make sense?

**Comment by JoeHegarty** [comment]
For more info on Observers and Streams see:

https://github.com/orbit/orbit/wiki/Concepts%3A-Streams
https://github.com/orbit/orbit/wiki/Concepts%3A-Observers

**Comment by JoeHegarty** [comment]
This has been idle for a while so I'm going to close it out. Please feel free to reopen if you have further questions.
