### ISSUE TITLE
Is there a way overcome chain blocking ?

### ISSUE THREAD

**Issue by mryvz** [orbit/orbit#274]
Hi, 
im calling  actor1.m1 method which calls actor2.m2 method _(example codes below)_. actor1 also being blocked until actor2 task is completed. Is there a way return actor2.m2 task and free actor1 from lock ?

```java
interface Actor2 extends Actor {
    //long blocking task
     public Task<String> m2();
}
```
```java
class Actor1Impl extends AbstracActor implements Actor1 {
     Actor2 actor2 = .... 
    // load actor2 etc  
    ....
    public Task<String> m1(){
      // doing my internal tasks
       ...
       // last task will be complated by actor2 and have no more internal job to do in this (act1) actor
       return Task.from(actor2.m2())
    }
    
}

```
also tried 
return Task.supplyAsync(actor2.m2());
return  Task.fromValue(actor2.m2()); // which causes not serializable exception 
....

Thanks.

**Comment by JoeHegarty** [comment]
I’m currently travelling but will be able to respond tomorrow. Sorry for the delay.

**Comment by JoeHegarty** [comment]
Chain blocking is typically desired in Orbit because otherwise you lose the guarantees that only one message can be running. 

In cases where you know it is safe to interleave messages, Orbit supports the concept of Reentrancy. See https://github.com/orbit/orbit/wiki/Concepts%3A-Reentrancy

Hopefully this will meet your needs. If not, let me know in which case the current behavior causes an issue and I may be able to think of another solution.

**Comment by mryvz** [comment]
Reentrant annotation will block calling thread too . Its not problem big problem for me , just wonder there is a method  something like  "Task.passFrom(act2.m2())" will return act2.m2() task and lave act 1 out of block chain would be usefull.

**Comment by JoeHegarty** [comment]
There is no way to overcome the chain blocking and still get a response, that's a core part of what Orbit guarantees with thread safety.
However, as I mentioned in issue #273 you are absolutely able to kick off a job on another thread pool and then use observers/streams to send a response.

**Comment by JoeHegarty** [comment]
For more info on Observers and Streams see:

https://github.com/orbit/orbit/wiki/Concepts%3A-Streams
https://github.com/orbit/orbit/wiki/Concepts%3A-Observers

**Comment by JoeHegarty** [comment]
This has been idle for a while so I'm going to close it out. Please feel free to reopen if you have further questions.
