### ISSUE TITLE
Request Actor Deactivation

### ISSUE THREAD

**Issue by JoeHegarty** [orbit/orbit#284]
Support a new API that allows users to request early deactivation of actors.
This is useful for optimization purposes.

**Comment by quilombodigital** [comment]
why not think about ACTOR.MOVE_TO(NODE) too, as a migration process? i.e.: move load to another node.

**Comment by JoeHegarty** [comment]
Yep, I think something like that would be a great addition @quilombodigital, but it's fairly hard to achieve with the current architecture.
We're planning to start work on Orbit 2.x in the new year so it seems like something to target for that.

**Comment by JoeHegarty** [comment]
Included in PR #286
