### ISSUE TITLE
orleans vs orbit

### ISSUE THREAD

**Issue by amit2103** [orbit/orbit#299]
Orleans seems to do consistent hashing and maintain a distributed key valye map to send data to the actor ?
Does orbit do something similar? Is there any performance benchmark for orbit vs orleans or akka ?

**Comment by JoeHegarty** [comment]
Orbit itself doesn't dictate how actors are located. This is instead offloaded to the `ClusterPeer` and we call that component the `ActorDirectory` and it sits alongside the `NodeDirectory` and `Messaging` to offer all the clustering capabilities.

The default `ClusterPeer` in Orbit is powered by Infinispan/JGroups (http://infinispan.org/) and it works very much like the implementation in Orleans, a distributed consistent key/value map.
However, there are alternative implementations. The most popular of which is using Redis. See https://github.com/orbit/orbit-redis-cluster

In terms of performance, I don't have any raw numbers but you should expect performance to be broadly in line with what other frameworks achieve dependent on your exact configuration and use case. 
On the scale size of things, Orbit is used to power deployed applications that can handle hundreds of thousands of requests a second so you can scale fairly linearly to extremely high use case scenarios.

Hopefully that answers your question. Let me know if not.

**Comment by amit2103** [comment]
@JoeHegarty Great answer. Why I am asking is I want to implement the Saga pattern with micro services with Orbit and try to create an application which will help in sustaning an enormous amount of sockets under load.

**Comment by JoeHegarty** [comment]
You absolutely should be able to do that with Orbit without too much trouble.
Let me know if you have any further questions or run into any trouble.
