### ISSUE TITLE
Gradle plugin - add dependency expression mechanism

### ISSUE THREAD

**Issue by cesarblum** [orbit/orbit#369]
When someone uses the Gradle plugin

```
plugins {
  id 'cloud.orbit.plugin'
}
```

We should make available an Orbit helper to specify dependencies (similar to what the Kotlin plugin does):

```
dependencies {
  implementation(orbit("core"))
}
```

**Comment by mattdkerr** [comment]
Is it possible to do it like kotlin-dsl does it in the plugins block?
```
 plugins {
    kotlin("jvm") ...
}
```

**Comment by cesarbs** [comment]
Yeah, that's the current plan actually. Something like

```
plugins {
  oribt("core", "runtime") ...
}
```
