### ISSUE TITLE
Orbit 2 client exceptions should be able to be thrown as original

### ISSUE THREAD

**Issue by mattdkerr** [orbit/orbit#418]
Scenario:
Create an actor in Kotlin code that executes "throw new IllegalArgumentException(...)" from the actor interface. Call that interface via the Orbit 2 client in Kotlin code and handle IllegalArgumentException as returning out a ResponseEntity with status code 404.

Expected:
the handling block is able to catch and return the proper web response to a web controller

Actual:
the handling block can't catch it because it is now wrapped in a RemoteException

**Comment by JoeHegarty** [comment]
What happens currently is RemoteException is thrown with the remote exception string in the message.

We should handle this the same as we handle method arg/response serialization on the JVM.
If the user both sides are JVM, we can simply serialize the exception as is.

For cross-platform we continue to use the RemoteException and eventually could define exceptions in the DSL.

**Comment by JoeHegarty** [comment]
This feature is now available in alpha 35.

Set the property `platformExceptions` in `OrbitClientConfig` to true to turn it on.
