### ISSUE TITLE
It looks like orbit is stale. Is the project still being worked on, just with no public releases?

### ISSUE THREAD

**Issue by marknefedov** [orbit/orbit#447]
If orbit was deprecated, what are you moved to?

**Comment by brettmorien** [comment]
As of right now, none of the original maintainers are spending any time maintaining this technology, and the main products within our company have deprecated it as a core technology. I wouldn't expect any significant support from this team. I personally don't even have the language tools installed any more to make changes.

**Comment by He-Pin** [comment]
@brettmorien What new technology replace orbit, thanks.

**Comment by brettmorien** [comment]
The main team using Orbit has moved away from the Actor Model in general, instead using custom intelligent routing for the scenario. There isn't any general-purpose replacement that would work in a similar way to Orbit.

I do think Orbit 2 is a pretty good update on the concept, but I don't anticipate anybody on our end dedicating time to it.

**Comment by He-Pin** [comment]
@brettmorien Thanks for sharing, can can't wait for the new Mass Effect ;)
